# Generated by Django 3.0.3 on 2020-03-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200307_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='method',
        ),
    ]
