# Generated by Django 3.0.3 on 2020-03-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_recipe_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.Recipe'),
        ),
    ]
